name: "New Feature"
description: Plan for a new feature
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: Please provide a clear and concise description of the feature you would like to see.
      placeholder: It would be better to have...
    validations:
      required: true
  - type: textarea
    id: plan
    attributes:
      label: Describe how to implement the feature
      description: Please provide a clear and concise description of how you would like to see the feature implemented.
      placeholder: It should be possible to...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: "Any additional information"
  - type: dropdown
    id: importance
    attributes:
      label: Importance
      description: How important is this feature to you?
      options:
        - nice to have
        - would make my life easier
        - i cannot use admin page without it
    validations:
      required: true
